### ISSUE TITLE
Layout improvements needed

### ISSUE THREAD

**Issue by vtainio** [futurice/vor#66]
- [x] "Connected, aware and safe" icons needs to be smaller and the gap between the icons and the red text should be bigger.
- [x] "Our sponsors, our inspiration" section's text should be the same width as other texts on the same page.
- [x] The gap between two lines in the headers such as in "How does it work" should be smaller.
- [x] The link to Github in "Ready to contribute" should have a similar style as other buttons in the page.

**Comment by luisramalho** [comment]
Fixed with these:
- 3fe08d5 - Ready to contribute button now uses the same style as other buttons
- fc2d6f2 - Margin between header and subheader is now smaller
- 3374f4f - Sponsors text is the same width as other texts on the same page
- bcd460e - Icons are smaller and there's more margin between them
