### ISSUE TITLE
Application short description in Play store is auto translated

### ISSUE THREAD

**Issue by kimmoahokas** [futurice/vor#78]
The application short description in Google Play store is auto-translated and that is bad. For example in Finnish it is "Uusi Esineiden internet toimisto kokemus". Please disable this feature or translate manually :)

**Comment by luisramalho** [comment]
I've tried to find that option but it doesn't seem to be available from the developer's console. It seems only the user can disable that feature, not sure.

> If users visit your app's Store Listing on Google Play in a language that you haven't translated, they can choose to view an automated translation of your app's page. Near the top of the page, there will be a notification that explains the translation has been done automatically, along with an option to view the Store Listing in its default language instead.

https://support.google.com/googleplay/android-developer/answer/3125566?hl=en

I have copy pasted the text from the English version to the Finnish version, so the auto translation should not happen, happy if someone contributes the Finnish translation.

**Comment by kimmoahokas** [comment]
Wow, that's just stupid behavior from Google.

If you want to translate it I think "Uusi esineiden Internetin toimistokokemus" would be quite ok translation. Google translation was quite close, just missed compound words and suffixes. However, I'm not sure whether it makes sense to translate that as everything else is in English.

**Comment by luisramalho** [comment]
Thanks @kimmoahokas! I've added your translation, I think it's good because the other description is basically repeating what was said before, so we duplicate the info but in different languages.

Regarding the behaviour, I don't think it is that bad, it kinda makes sense that the user has to opt-out of automatic translations... that would also be my preferred option if I'm checking apps in a foreign language.
